# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8da37a84a55bcee34d59da8f4224edac8f62debb814bd5dc0e4ba6417994079ce0ec3ef3347c7ed9c377974e2327d5f0d26ff72723238c06e80a23d25b00a2f

test:
  secret_key_base: adb1c1bc2a77e5ee8958c5ff5e445a0a7824afd2cd19ec5b2d7d829333ffbc8d9991350dfa10c1a8ba03a8970fc9c983a6168835ca17a707fa3dfc02b2be6f5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
